export const SET_QUESTIONS = 'SET_QUESTIONS'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_QUESTION_STATE = 'SET_QUESTION_STATE'

export const SET_QUESTION_RESULT = 'SET_QUESTION_RESULT'
